steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/gen-lang-client-0010578590/cloud-run-source-deploy/khetesh-deore-devflow/devflow-frontend:latest'
      - '--build-arg'
      - 'VITE_API_URL=https://devflow-1063807782201.asia-south1.run.app/api/v1'
      - '--build-arg'
      - 'VITE_SOCKET_URL=https://devflow-1063807782201.asia-south1.run.app'
      - '-f'
      - 'Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/gen-lang-client-0010578590/cloud-run-source-deploy/khetesh-deore-devflow/devflow-frontend:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'devflow-frontend-new'
      - '--image'
      - 'asia-south1-docker.pkg.dev/gen-lang-client-0010578590/cloud-run-source-deploy/khetesh-deore-devflow/devflow-frontend:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'asia-south1-docker.pkg.dev/gen-lang-client-0010578590/cloud-run-source-deploy/khetesh-deore-devflow/devflow-frontend:latest'
